[package]
name = "llama-rs"
version = { workspace = true }
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggml = { path = "../ggml" }
llama-loader = { path = "../llama-loader" }

bytemuck = "1.13.1"
partial_sort = "0.2.0"
thiserror = "1.0"
rand = { workspace = true }
serde = { version = "1.0.156", features = ["derive"] }
serde_bytes = "0.11"
bincode = "1.3.3"
memmap2 = { version = "0.5.10", optional = true }

# Used for the `convert` feature
serde_json = { version = "1.0.94", optional = true }
protobuf = { version = "= 2.14.0", optional = true }
rust_tokenizers = { version = "3.1.2", optional = true }

[features]
convert = ["dep:serde_json", "dep:protobuf", "dep:rust_tokenizers"]

# broken atm, see https://github.com/rustformers/llama-rs/pull/114#issuecomment-1500337463
mmap = ["dep:memmap2"]
